# Generated by Django 4.2.4 on 2023-08-07 17:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0002_car_creation_date_car_description_car_horse_power"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="creation_date",
            field=models.DateField(null=True),
        ),
    ]
