# Generated by Django 4.2.4 on 2023-08-07 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_alter_car_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='description',
            field=models.TextField(default='wow'),
        ),
    ]
