# Generated by Django 4.1.7 on 2023-08-07 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_alter_literaryfromat_format'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiteraryFormat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(max_length=63)),
            ],
        ),
        migrations.DeleteModel(
            name='LiteraryFromat',
        ),
    ]
