# Generated by Django 4.1.7 on 2023-08-07 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0005_alter_book_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="format",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="book_set",
                to="db.literaryformat",
            ),
        ),
    ]
