# Generated by Django 4.1.7 on 2023-08-10 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0008_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="authors",
            field=models.ManyToManyField(related_name="by_author", to="db.author"),
        ),
        migrations.AlterField(
            model_name="book",
            name="format",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="by_format",
                to="db.literaryformat",
            ),
        ),
    ]
