# Generated by Django 4.1.7 on 2023-08-10 15:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0009_book_authors_alter_book_format"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="authors",
            new_name="author",
        ),
    ]
