# Generated by Django 4.1.7 on 2023-08-10 15:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0011_alter_book_author"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="author",
            new_name="authors",
        ),
    ]
