# Generated by Django 4.1.7 on 2023-08-10 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0012_rename_author_book_authors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='authors',
        ),
    ]
