# Generated by Django 4.1.7 on 2023-08-10 20:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0013_remove_book_authors"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="authors",
            field=models.ManyToManyField(to="db.author"),
        ),
    ]
