# Generated by Django 4.1.7 on 2023-08-22 22:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bus_station", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="bus",
            table="bus",
        ),
    ]
