# Generated by Django 4.1.7 on 2023-08-22 22:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bus_station", "0002_alter_bus_table"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bus",
            options={"verbose_name": "bus", "verbose_name_plural": "buses"},
        ),
        migrations.AlterModelTable(
            name="bus",
            table=None,
        ),
    ]
