# Generated by Django 4.1.7 on 2023-08-22 23:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bus_station", "0004_alter_order_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trip",
            name="source",
            field=models.CharField(db_index=True, max_length=63),
        ),
    ]
