# Generated by Django 4.1.7 on 2023-08-08 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0007_alter_book_format'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caffee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_index', models.CharField(max_length=32)),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='LiteraryFormat',
        ),
        migrations.AddField(
            model_name='caffee',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.place'),
        ),
    ]
