# Generated by Django 4.1.7 on 2023-08-08 00:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0008_caffee_place_delete_book_delete_literaryformat_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Caffee",
            new_name="Caffe",
        ),
        migrations.AddField(
            model_name="place",
            name="address",
            field=models.CharField(default="address", max_length=255),
        ),
    ]
