# Generated by Django 4.1.7 on 2023-08-08 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0012_alter_caffe_place"),
    ]

    operations = [
        migrations.AlterField(
            model_name="caffe",
            name="place",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="db.place"
            ),
        ),
    ]
