# Generated by Django 4.0.2 on 2023-12-22 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_module', '0007_alter_guild_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruit',
            name='uptime',
        ),
        migrations.AddField(
            model_name='recruit',
            name='rt_end',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='recruit',
            name='rt_start',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='recruit',
            name='uptime_days',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
