# Generated by Django 4.0.2 on 2023-12-19 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_module', '0004_alter_guild_teams'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='guild',
        ),
    ]
