# Generated by Django 4.0.2 on 2023-12-19 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search_module', '0005_remove_team_guild'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plannedactivity',
            name='by_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search_module.team'),
        ),
    ]
