x = "Hello, my name is Elias"
len(x)
x[len(x) - 1]
x.count("l")
capitalized_text = x.capitalize()
print(capitalized_text)
upper_cased = x.upper()
print(upper_cased)
lower_cased = x.lower()
print(lower_cased)
print(upper_cased.isupper())
print(lower_cased.islower())
print(x.islower())
print("__________________________")
print(x.find("m", 4, 15))
print("__________________________")
print(x.find("my"))
print("__________________________")
print("123abc".isalnum())
print("123abc!".isalnum())
print("__________________________")

print("abc".isalpha())
print("123abc".isalpha())
print("__________________________")
print("   ".isspace())
print("".isspace())
print("1".isspace())
empty_string = ""
print("__________________________")
print(empty_string.strip(" ") == "")

if not empty_string == "":
    print("not empty")
else:
    print("empty")
print("__________________________")
print("__________________________")
print("__________________________")
h = "hello"
print(h.startswith("he"))
print(h.endswith("lo"))
print("__________________________")
print("__________________________")
split = h.split("l")
print(type(split))
print(split)
split = h.split("e")
print(split)
print("__________________________")
print("__________________________")
data = "12;10;8;10"
split_data = data.split(";")
print(type(split_data))
print(split_data)
print("__________________________")
print("__________________________")
data = "12;10;8;10"
data = data.partition(";")
print(type(data))
print(data)
