# Generated by Django 4.0.2 on 2023-12-19 16:49

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Guild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('faction', models.CharField(choices=[('Alliance', 'Alliance'), ('Horde', 'Horde')], default='Unrecognized', max_length=10)),
                ('highest_progress', models.CharField(max_length=5)),
                ('discord_link', models.CharField(blank=True, max_length=255, null=True)),
                ('apply_link', models.CharField(blank=True, max_length=255, null=True)),
                ('wcl_link', models.URLField(blank=True, null=True, verbose_name='wcl_link')),
                ('guild_note', models.CharField(blank=True, max_length=1000, null=True)),
                ('avatar', models.CharField(blank=True, max_length=255, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guild_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InGameClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='InGameSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlannedActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raid_day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=255)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=255)),
                ('team_size', models.IntegerField()),
                ('team_progress', models.IntegerField(default=0)),
                ('active_search', models.BooleanField(default=True)),
                ('team_note', models.CharField(blank=True, max_length=1000, null=True)),
                ('loot_system', models.CharField(choices=[('Loot Council', 'Loot Council'), ('EPGP', 'EPGP'), ('DKP', 'DKP'), ('SR', 'SR'), ('BIS > MS > OS roll', 'BIS > MS > OS roll'), ('GDKP', 'GDKP'), ('Roll', 'Roll'), ('Other', 'Other')], default='Other', max_length=20)),
                ('activities', models.ManyToManyField(related_name='activities', to='search_module.PlannedActivity')),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search_module.guild')),
                ('looking_for', models.ManyToManyField(related_name='looking_for', to='search_module.Character')),
            ],
        ),
        migrations.CreateModel(
            name='Recruit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=255)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('wcl', models.IntegerField(blank=True, null=True)),
                ('character', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='search_module.character')),
                ('uptime', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruit_uptime', to='search_module.plannedactivity')),
            ],
        ),
        migrations.AddField(
            model_name='guild',
            name='teams',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guid_teams', to='search_module.team'),
        ),
        migrations.AddField(
            model_name='character',
            name='class_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_class', to='search_module.ingameclass'),
        ),
        migrations.AddField(
            model_name='character',
            name='spec_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_spec', to='search_module.ingamespec'),
        ),
        migrations.AddField(
            model_name='user',
            name='guild',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_guild', to='search_module.guild'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
