# Generated by Django 4.0.2 on 2023-12-28 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_module', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(fields=('team_name', 'guild'), name='unique_team_guild'),
        ),
    ]
