# Generated by Django 4.0.2 on 2023-12-29 05:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("search_module", "0002_team_unique_team_guild"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="guild",
            options={"ordering": ["?"], "verbose_name_plural": "Guilds"},
        ),
    ]
