# Generated by Django 4.0.2 on 2023-12-29 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_module', '0003_alter_guild_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['?'], 'verbose_name_plural': 'Teams'},
        ),
    ]
