# Generated by Django 4.0.2 on 2023-12-29 08:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("search_module", "0006_alter_recruit_discord_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recruit",
            name="nickname",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
