# Generated by Django 4.0.2 on 2023-12-21 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_module', '0006_alter_plannedactivity_by_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guild',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
