# Generated by Django 4.0.2 on 2023-12-29 09:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("search_module", "0007_alter_recruit_nickname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recruit",
            name="discord_tag",
            field=models.CharField(blank=True, default="unknown", max_length=255),
        ),
    ]
