# Generated by Django 4.0.2 on 2023-12-22 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_module', '0008_remove_recruit_uptime_recruit_rt_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='required_active_days_amount',
            field=models.IntegerField(default=0),
        ),
    ]
