# Generated by Django 4.0.2 on 2023-12-22 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search_module', '0009_team_required_active_days_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guild',
            name='teams',
        ),
        migrations.RemoveField(
            model_name='team',
            name='activities',
        ),
        migrations.AddField(
            model_name='team',
            name='guild',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='search_module.guild'),
        ),
    ]
