# Generated by Django 4.0.2 on 2023-12-22 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search_module', '0010_remove_guild_teams_remove_team_activities_team_guild'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='guild',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search_module.guild'),
        ),
    ]
