# Generated by Django 4.0.2 on 2023-12-22 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_module', '0011_alter_team_guild'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_name',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
