# Generated by Django 4.0.2 on 2023-12-22 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_module', '0013_guild_teams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
