# Generated by Django 4.0.2 on 2023-12-22 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_module', '0017_alter_user_guild'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='guild',
        ),
    ]
