# Generated by Django 4.0.2 on 2023-12-22 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_module', '0018_remove_user_guild'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='todelete',
            field=models.CharField(default='asd', max_length=1),
            preserve_default=False,
        ),
    ]
